version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://json-server:3001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - json-server
    networks:
      - app-network

  json-server:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./db.json:/app/db.json
      - ./package.json:/app/package.json
    ports:
      - "3001:3001"
    command: npx json-server --watch db.json --port 3001 --host 0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
